name: Release builder

on:
  push:
    tags:
      - v*

jobs:
  tag-push-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: .github/release-configuration.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleare from cz tags
        id: clear_changelog
        uses: badygin-yakov/clear-changelog@master
        with:
          changelog: ${{ steps.github_release.outputs.changelog }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.clear_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}